name: minions-jobs-web
project_scope: child
child_type: web-app
parent_project: minions-jobs-workspace
description: Standard compliance definition for minions-jobs-web
priority: high
deploy_url: null
tags: null
category: minion-toolbox
